[run]
seed = 78231

[dir]
experiment = '../experiments'
train = '../data/patches/train'
valid = '../data/patches/valid'
run = '../experiments/01_vgg_v3_relu'
[dir.scaler]
    mean = '../data/patches/mean_1980_2004.nc'
    std = '../data/patches/std_1980_2004.nc'

[torch]
matmul_precision = "medium"
dtype = 'torch.float32'

[lightning]
accelerator = "cpu"
precision = "32-true"

[data]
drivers = ['fg10', 'i10fg', 'msl', 't_500', 't_300', 'vo_850']
targets = ['patch_cyclone']
label_no_cyclone = -1.0

[model]
monitor = 'val_loss'
cls = 'VGG_V3'
metrics = []
    [model.args]
    in_channels = 6
    out_channels = 2
    activation = 'nn.ReLU'
    init_std = 0.05

[loss]
cls = "nn.L1Loss"
[loss.args]

[optimizer]
cls = "torch.optim.AdamW"
    [optimizer.args]
        lr = 5e-4
        betas = [0.9, 0.95]
        weight_decay = 5e-6

[scheduler]
    [scheduler.warmup]
        total_iters = 20 # warmup epochs
        start_factor = 0.0001
        end_factor = 1.0
    [scheduler.annealing]
        eta_min = 5e-5 # minimum learning rate

[train]
epochs = 1
batch_size = 128
drop_remainder = true
accumulation_steps = 1
