[run]
seed = 42
use_case = 'gnn'

[dir]
experiment = '../experiments'
run = '../experiments/graphunet'
train = '../data/patches/train'
valid = '../data/patches/valid'
test = '../data/patches/test'
scaler = '../data/patches/scaler_1980_2009.nc'

[torch]
matmul_precision = "medium"
dtype = 'torch.float32'

[lightning]
accelerator = "cuda"
precision = "32-true"

[data]
drivers = ['fg10', 'i10fg', 'msl', 't_500', 't_300', 'vo_850']
targets = ['density_map_tc']

[model]
cls = 'GraphUNet'
metrics = []
    [model.args]
    in_channels = 6
    hid_channels = 64
    out_channels = 1
    K_pool = 800
    nodes_per_graph = 1600 # 40x40 grids translate to 1600 nodes per graph
    edge_dropout_rate = 0.2
    node_dropout_rate = 0.6
    activation = 'nn.Sigmoid()'

[loss]
cls = 'nn.BCELoss'
    [loss.args]

[optimizer]
cls = 'torch.optim.Adam'
    [optimizer.args]
    lr = 0.001
    betas = [0.9, 0.999]
    eps = 1e-07
    weight_decay = 0
    amsgrad = false

[scheduler]
    [scheduler.annealing]
    [scheduler.warmup]
    total_iters = 5 # warmup epochs

[train]
epochs = 1
batch_size = 512
augmentation = true
drop_remainder = true
accumulation_steps = 1
