[run]
seed = 91723

[dir]
experiment = '../experiments'
train = '../data/patches/train'
valid = '../data/patches/valid'
run = 'example_train'
[dir.scaler]
    mean = '../data/patches/mean_1980_2004.nc'
    std = '../data/patches/std_1980_2004.nc'

[torch]
matmul_precision = "medium"
dtype = 'torch.float32'

[lightning]
accelerator = "cpu" # "cuda"
precision = "32-true"

[data]
drivers = ['fg10', 'i10fg', 'msl', 't_500', 't_300', 'vo_850']
targets = ['patch_cyclone']
label_no_cyclone = -1.0

[model]
monitor = 'val_loss'
cls = 'tc.models.VGG_V3'
metrics = []
    [model.args]
    in_channels = 6
    out_channels = 2
    activation = 'nn.ReLU'
    kernel_size = 3
    init_std = 0.05

[loss]
cls = "nn.L1Loss"
[loss.args]

[optimizer]
cls = "torch.optim.Adam"
    [optimizer.args]
    lr = 0.0001
    betas = [0.9, 0.999]
    eps = 1e-7

[scheduler]
[scheduler.args]

[train]
epochs = 10
batch_size = 32
drop_remainder = true
accumulation_steps = 1
